// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    BaseLayout: typeof import('./src/layouts/base.vue')['default']
    GirlsIntro: typeof import('./src/components/GirlsIntro.mdx')['default']
    Heimu: typeof import('./src/components/Heimu.vue')['default']
    Island: typeof import('./node_modules/.pnpm/registry.npmmirror.com+iles@0.9.5_sass@1.63.6/node_modules/iles/dist/client/app/components/Island.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    WaifuCard: typeof import('./src/components/WaifuCard.vue')['default']
  }
}
