# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Submodules
      run: |
        git submodule update --init --remote
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update submodules" || echo "ignore commit failure, proceed"
        git push || echo "ignore commit failure, proceed"
      # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
          version: 8.6.6
    - name: Install dependencies
      run: pnpm install
    - name: build
      run: pnpm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ghtoken }}
        publish_dir: ./dist
